### PR TITLE
Fix incorrectly identified file after a reload using the Enter key

### PR DESCRIPTION
**Pull request by aybe**
I've been scratching my head on why my PSX hacking stuff wasn't working... 😤🤬🤣 

But in turned out there was a simple bug here, EZ to fix, the file offset needs to be reset for correct re-reading. 😀

Cheers!

### CODE REVIEW

**Comment by aybe** [comment]
Here are the updated builds: https://github.com/aybe/PsxVram-SDL/releases 😃

**Comment by romhack** [comment]
Thanks for fixing!

**Comment by aybe** [comment]
@romhack Seems like you forgot the most important PR😄, here it is but without cleanup so it's easier for you to look at: #8 😀

**Comment by romhack** [comment]
Thanks again for support! :) Unfortunately I don't have much time nowadays for thorough review.

**Comment by aybe** [comment]
No problem mate, take care! 😀

**Pull request closed without merging**
